# This rule is not used by the project blockchain-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to infra.blockchain.corp resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: blockchain-operator
    app.kubernetes.io/managed-by: kustomize
  name: ethereumnode-viewer-role
rules:
- apiGroups:
  - infra.blockchain.corp
  resources:
  - ethereumnodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.blockchain.corp
  resources:
  - ethereumnodes/status
  verbs:
  - get
